export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'AUTH/LOGIN_FAILURE';
export const LOGOUT = 'AUTH/LOGOUT';
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'AUTH/REGISTER_FAILURE';

export const FORM_SUCCESS = 'FORM/FORM_SUCCESS';
